-- ============================================================
-- CareConnect demo seed data
-- Generated by scripts/generate-seed-sql.js
-- Generated at: 2026-05-02T19:29:21.840Z
-- All users password: Password123!
-- ============================================================

-- 1. Users (auth)
INSERT INTO users (user_id, email, password_hash, role) VALUES
  (uuid_to_bin('c849af49-3045-4636-862c-126f3d8d0e5b'),   'admin@careconnect.com',     '$2b$12$guy2LlxMduNdzhZv.e159.LrdMwJqXbU5QpiDTdJGI3jmoKPdxU5y', 'admin'),
  (uuid_to_bin('5cc9b2b1-ae8a-4669-94a4-8db0a7ae4817'),   'maria.garcia@example.com',  '$2b$12$guy2LlxMduNdzhZv.e159.LrdMwJqXbU5QpiDTdJGI3jmoKPdxU5y', 'caregiver'),
  (uuid_to_bin('a39b36ac-7654-4dee-b925-8cc7aab427fc'),   'james.wilson@example.com',  '$2b$12$guy2LlxMduNdzhZv.e159.LrdMwJqXbU5QpiDTdJGI3jmoKPdxU5y', 'caregiver'),
  (uuid_to_bin('f5b35e19-4d24-46d8-bcbe-732c42f78f19'), 'dorothy.chen@example.com',  '$2b$12$guy2LlxMduNdzhZv.e159.LrdMwJqXbU5QpiDTdJGI3jmoKPdxU5y', 'care_receiver');

-- 2. Caregiver profiles (caregiver_id = user_id)
INSERT INTO caregiver (caregiver_id, first_name, last_name, email, phone, is_verified, rating) VALUES
  (uuid_to_bin('5cc9b2b1-ae8a-4669-94a4-8db0a7ae4817'), 'Maria', 'Garcia',  'maria.garcia@example.com',  '212-555-0101', 1, 4.85),
  (uuid_to_bin('a39b36ac-7654-4dee-b925-8cc7aab427fc'), 'James', 'Wilson',  'james.wilson@example.com',  '212-555-0102', 1, 4.92);

-- 3. Care receiver profile (care_receiver_id = user_id)
INSERT INTO careReceiver (care_receiver_id, first_name, last_name, birthday, sex) VALUES
  (uuid_to_bin('f5b35e19-4d24-46d8-bcbe-732c42f78f19'), 'Dorothy', 'Chen', '1948-03-15', 'female');

-- 4. Default address for Dorothy (so booking has somewhere to send the caregiver)
INSERT INTO address (address_id, care_receiver_id, nickname, address_line1, city, state, zip_code, latitude, longitude, is_primary) VALUES
  (uuid_to_bin('4a952fb8-2695-4266-92f1-acdfc773d03c'), uuid_to_bin('f5b35e19-4d24-46d8-bcbe-732c42f78f19'), 'home', '123 Main St', 'New York', 'NY', '10001', 40.7484, -73.9967, 1);

-- ============================================================
-- Verify
-- ============================================================
-- SELECT email, role FROM users;
-- SELECT first_name, last_name, rating FROM caregiver;
-- SELECT first_name, last_name, birthday FROM careReceiver;
-- SELECT address_line1, city, state FROM address;

-- ============================================================
-- IDs for reference (UUIDs as strings, in case you need them)
-- ============================================================
-- admin   user_id:           c849af49-3045-4636-862c-126f3d8d0e5b
-- Maria   caregiver_id:      5cc9b2b1-ae8a-4669-94a4-8db0a7ae4817
-- James   caregiver_id:      a39b36ac-7654-4dee-b925-8cc7aab427fc
-- Dorothy care_receiver_id:  f5b35e19-4d24-46d8-bcbe-732c42f78f19
-- Dorothy address_id:        4a952fb8-2695-4266-92f1-acdfc773d03c
